name: git_revision
version: 0.6.0
description: Revision calculator for git projects

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  args: '^1.2.0'

dev_dependencies:
  test: '^1.2.0'
  mockito: '^3.0.0-beta+1'
  dart_style: '^1.1.2'
  path: ^1.6.2
  archive: '>=1.0.0 <3.0.0'

executables:
  # a valid dart filename doesn't contain a dash -> remapping
  git-revision: git_revision
